apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Chart.Name }}-ndn-net
  namespace: oai
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "mode": "bridge",
      "master": "{{ .Values.multus.hostInterface | trim }}",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "{{ .Values.multus.ndnIP }}/{{ .Values.multus.ndnNetmask | trim }}",
            "gateway": "{{ .Values.multus.ndnGateway | trim }}"
          }
        ],
        "routes": [
          {
            "dst": "0.0.0.0/0"
          }
        ],
        "dns": {
          "nameservers": ["8.8.8.8", "8.8.4.4"]
        }
      }
    }
